server:
  port: 8081
spring:
  config:
    import: optional:file:.env[.properties]
  cloud:
    config:
      server:
        git:
          uri: ${GIT_URI}
          default-label: master
          username: ${GIT_USERNAME}
          password: ${GIT_PASSWORD}

